### ISSUE TITLE
Roadmap to arrow work

### ISSUE THREAD

**Issue by tli2** [cmu-db/noisepage#248]
I am opening this issue to keep track of the features I need to think through and implement as well as the experiments I need to run for arrow. 
### New features:
- [x] access-observer on GC to determine whether a block is hot or cold
- [x] intra-block compaction (eliminate gaps) (Maybe we should do inter-block instead?)
- [x] GC for varlens
- [x] Gather varlen into contiguous chunk on compaction
- [ ] RPC for serving out arrow
- [x] Alternative concurrency control for "cold" blocks (reader-writer latch should be good?)

### Experiments:
- [x] (strawman motivation graph)  loading some trivial dataset (e.g. 1 million identical tuples) into arrow from Postgres vs. loading directly into Arrow via hardcoded c++ API
- [x] Block Transformation vs. constructing from arrow API
- [ ] Pandas on Postgres(maybe?) vs. Pandas on Terrier with arrow (maybe also plus Pandas on Arrow directly)
- [x] TPC-C throughput vs. some baseline OLTP system (or just throughput. the audience should know what a good throughput is)
- [x] TPC-C throughput with/without background compaction (to prove that our proposed solution is lightweight)

### Supporting features (so that we can run experiments)
- [x] Hard-coded plan for TPC-C
- [x] Indexes
- [x] (Maybe ?) The network layer

**Comment by lmwnshn** [comment]
Unless @tli2 objects, closing this.
